export const colors = {
  primary: '#232f3f',
  secondary: '#fe9900',
  danger: "#D0181B",
  platinum: '#E3E2E0',
  white: 'white',
  darkBlue: '#174882',
  gray: '#a6a6a8',
  lightgray: '#f0f0f0',
  lightgreen: '#f1ffe6',
  green: '#245b00',
  black: 'black'

};
export const fonts = {
  sfDisplay: {
    black: 'SF-Pro-Display-Black',
    blackItalic: 'SF-Pro-Display-BlackItalic',
    bold: 'SF-Pro-Display-Bold',
    boldItalic: 'SF-Pro-Display-BoldItalic',
    heavy: 'SF-Pro-Display-Heavy',
    heavyItalic: 'SF-Pro-Display-HeavyItalic',
    light: 'SF-Pro-Display-Light',
    lightItalic: 'SF-Pro-Display-LightItalic',
    medium: 'SF-Pro-Display-Medium',
    mediumItalic: 'SF-Pro-Display-MediumItalic',
    regular: 'SF-Pro-Display-Regular',
    regularItalic: 'SF-Pro-Display-RegularItalic',
    semiBold: 'SF-Pro-Display-Semibold',
    semiBoldItalic: 'SF-Pro-Display-SemiboldItalic',
    thin: 'SF-Pro-Display-Thin',
    thinItalic: 'SF-Pro-Display-ThinItalic',
    ultraLight: 'SF-Pro-Display-Ultralight',
    ultraLightItalic: 'SF-Pro-Display-UltralightItalic',
  },
  sfText: {
    bold: 'SF-Pro-Text-Bold',
    boldItalic: 'SF-Pro-Text-BoldItalic',
    heavy: 'SF-Pro-Text-Heavy',
    heavyItalic: 'SF-Pro-Text-HeavyItalic',
    light: 'SF-Pro-Text-Light',
    lightItalic: 'SF-Pro-Text-LightItalic',
    medium: 'SF-Pro-Text-Medium',
    mediumItalic: 'SF-Pro-Text-MediumItalic',
    regular: 'SF-Pro-Text-Regular',
    regularItalic: 'SF-Pro-Text-RegularItalic',
    semiBold: 'SF-Pro-Text-Semibold',
    semiBoldItalic: 'SF-Pro-Text-SemiboldItalic',
    thin: 'SF-Pro-Text-Thin',
    thinItalic: 'SF-Pro-Text-ThinItalic',
    ultraLight: 'SF-Pro-Text-Ultralight',
    ultraLightItalic: 'SF-Pro-Text-UltralightItalic',
  },
  poppins: {
    semiBold: 'Poppins-SemiBold',
    regular: 'Poppins-Regular',
    medium: 'Poppins-Medium',
    light: 'Poppins-Light.ttf',
    bold: 'Poppins-Bold',
    extraBold: 'Poppins-ExtraBold',
    black: 'Poppins-Black',
  },
};

export const selectedFont = 'sfText';
